; Song Untitled in Lightweight format (V1).
; Generated by Arkos Tracker 2.

DeckHero_Start
DeckHero_StartDisarkGenerateExternalLabel

DeckHero_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
DeckHero_DisarkByteRegionEnd0
DeckHero_DisarkPointerRegionStart1
	dw DeckHero_FmInstrumentTable
	dw DeckHero_ArpeggioTable
	dw DeckHero_PitchTable
; Table of the Subsongs.
	dw DeckHero_Subsong0
DeckHero_DisarkPointerRegionEnd1

; The Arpeggio table.
DeckHero_ArpeggioTable
DeckHero_DisarkWordRegionStart2
	dw 0
DeckHero_DisarkWordRegionEnd2
DeckHero_DisarkPointerRegionStart3
DeckHero_DisarkPointerRegionEnd3

; The Pitch table.
DeckHero_PitchTable
DeckHero_DisarkWordRegionStart4
	dw 0
DeckHero_DisarkWordRegionEnd4
DeckHero_DisarkPointerRegionStart5
DeckHero_DisarkPointerRegionEnd5

; The FM Instrument table.
DeckHero_FmInstrumentTable
DeckHero_DisarkPointerRegionStart6
	dw DeckHero_FmInstrument0
	dw DeckHero_FmInstrument1
	dw DeckHero_FmInstrument2
	dw DeckHero_FmInstrument3
	dw DeckHero_FmInstrument4
	dw DeckHero_FmInstrument5
DeckHero_DisarkPointerRegionEnd6

DeckHero_DisarkByteRegionStart7
DeckHero_FmInstrument0
	db 255	; Speed.

DeckHero_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
DeckHero_DisarkPointerRegionStart8
	dw DeckHero_FmInstrument0Loop	; Loops.
DeckHero_DisarkPointerRegionEnd8

DeckHero_FmInstrument1
	db 4	; Speed.

	db 61	; Volume: 15.

	db 57	; Volume: 14.

	db 53	; Volume: 13.

	db 49	; Volume: 12.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
DeckHero_DisarkPointerRegionStart9
	dw DeckHero_FmInstrument0Loop	; Loop to silence.
DeckHero_DisarkPointerRegionEnd9

DeckHero_FmInstrument2
	db 0	; Speed.

	db 61	; Volume: 15.

	db 57	; Volume: 14.

	db 53	; Volume: 13.

	db 49	; Volume: 12.

	db 45	; Volume: 11.

	db 41	; Volume: 10.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
DeckHero_DisarkPointerRegionStart10
	dw DeckHero_FmInstrument0Loop	; Loop to silence.
DeckHero_DisarkPointerRegionEnd10

DeckHero_FmInstrument3
	db 2	; Speed.

	db 248	; Volume: 15.
	db 1	; Noise.

	db 240	; Volume: 14.
	db 1	; Noise.

	db 232	; Volume: 13.
	db 1	; Noise.

	db 224	; Volume: 12.
	db 1	; Noise.

	db 216	; Volume: 11.
	db 1	; Noise.

	db 200	; Volume: 9.
	db 1	; Noise.

	db 192	; Volume: 8.
	db 1	; Noise.

	db 184	; Volume: 7.
	db 1	; Noise.

	db 176	; Volume: 6.
	db 1	; Noise.

	db 168	; Volume: 5.
	db 1	; Noise.

	db 160	; Volume: 4.
	db 1	; Noise.

	db 152	; Volume: 3.
	db 1	; Noise.

	db 144	; Volume: 2.
	db 1	; Noise.

	db 136	; Volume: 1.
	db 1	; Noise.

	db 4	; End the instrument.
DeckHero_DisarkPointerRegionStart11
	dw DeckHero_FmInstrument0Loop	; Loop to silence.
DeckHero_DisarkPointerRegionEnd11

DeckHero_FmInstrument4
	db 0	; Speed.

	db 248	; Volume: 15.
	db 1	; Noise.

	db 121	; Volume: 14.
	dw 150	; Pitch: 150.

	db 117	; Volume: 13.
	dw 300	; Pitch: 300.

	db 113	; Volume: 12.
	dw 400	; Pitch: 400.

	db 109	; Volume: 11.
	dw 500	; Pitch: 500.

	db 105	; Volume: 10.
	dw 600	; Pitch: 600.

	db 4	; End the instrument.
DeckHero_DisarkPointerRegionStart12
	dw DeckHero_FmInstrument0Loop	; Loop to silence.
DeckHero_DisarkPointerRegionEnd12

DeckHero_FmInstrument5
	db 0	; Speed.

	db 248	; Volume: 15.
	db 1	; Noise.

	db 249	; Volume: 14.
	db 1	; Arpeggio: 0.
	db 2	; Noise: 2.
	dw -10	; Pitch: -10.

	db 241	; Volume: 12.
	db 1	; Arpeggio: 0.
	db 3	; Noise: 3.
	dw -30	; Pitch: -30.

	db 216	; Volume: 11.
	db 1	; Noise.

	db 80	; Volume: 10.

	db 208	; Volume: 10.
	db 1	; Noise.

	db 200	; Volume: 9.
	db 1	; Noise.

	db 192	; Volume: 8.
	db 1	; Noise.

	db 184	; Volume: 7.
	db 1	; Noise.

	db 176	; Volume: 6.
	db 1	; Noise.

	db 168	; Volume: 5.
	db 1	; Noise.

	db 160	; Volume: 4.
	db 1	; Noise.

	db 144	; Volume: 2.
	db 1	; Noise.

	db 136	; Volume: 1.
	db 1	; Noise.

	db 4	; End the instrument.
DeckHero_DisarkPointerRegionStart13
	dw DeckHero_FmInstrument0Loop	; Loop to silence.
DeckHero_DisarkPointerRegionEnd13

DeckHero_DisarkByteRegionEnd7
DeckHero_Subsong0DisarkByteRegionStart0
; Song Untitled, Subsong 0 - Subsong - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

DeckHero_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
DeckHero_Subsong0loop
	db 7	; State byte.
	db 11	; New speed.
	db 63	; New height.
DeckHero_Subsong0DisarkPointerRegionStart1
	dw DeckHero_Subsong0_Track0, DeckHero_Subsong0_Track1, DeckHero_Subsong0_Track2
DeckHero_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
DeckHero_Subsong0DisarkPointerRegionStart2
	dw DeckHero_Subsong0_Track4, DeckHero_Subsong0_Track5, DeckHero_Subsong0_Track6
DeckHero_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
DeckHero_Subsong0DisarkPointerRegionStart3
	dw DeckHero_Subsong0_Track4, DeckHero_Subsong0_Track5, DeckHero_Subsong0_Track6
DeckHero_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
DeckHero_Subsong0DisarkPointerRegionStart4
	dw DeckHero_Subsong0_Track4, DeckHero_Subsong0_Track5, DeckHero_Subsong0_Track6
DeckHero_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
DeckHero_Subsong0DisarkPointerRegionStart5
	dw DeckHero_Subsong0_Track3, DeckHero_Subsong0_Track7, DeckHero_Subsong0_Track3
DeckHero_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
DeckHero_Subsong0DisarkPointerRegionStart6
	dw DeckHero_Subsong0_Track3, DeckHero_Subsong0_Track7, DeckHero_Subsong0_Track3
DeckHero_Subsong0DisarkPointerRegionEnd6
; The tracks.

	db 0	; End of the subsong.
DeckHero_Subsong0DisarkPointerRegionStart7
	dw DeckHero_Subsong0loop
DeckHero_Subsong0DisarkPointerRegionEnd7

; The Tracks.
DeckHero_Subsong0_Track0
	db 213	; Note: 45.
	db 2	; New instrument: 1.
	db 128	; Volume + possible Pitch up/down.
	db 61, 14	; Long wait: 15.

	db 22	; Note: 46.
	db 61, 14	; Long wait: 15.

	db 23	; Note: 47.
	db 61, 14	; Long wait: 15.

	db 24	; Note: 48.
	db 61, 14	; Long wait: 15.


DeckHero_Subsong0_Track1
	db 213	; Note: 45.
	db 2	; New instrument: 1.
	db 128	; Volume + possible Pitch up/down.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 150	; Note: 46.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 151	; Note: 47.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.


DeckHero_Subsong0_Track2
	db 216	; Note: 48.
	db 6	; New instrument: 3.
	db 128	; Volume + possible Pitch up/down.
	db 61, 62	; Long wait: 63.


DeckHero_Subsong0_Track3
	db 61, 63	; Long wait: 64.


DeckHero_Subsong0_Track4
	db 149	; Note: 45.
	db 2	; New instrument: 1.
	db 61, 14	; Long wait: 15.

	db 22	; Note: 46.
	db 61, 14	; Long wait: 15.

	db 23	; Note: 47.
	db 61, 14	; Long wait: 15.

	db 24	; Note: 48.
	db 61, 14	; Long wait: 15.


DeckHero_Subsong0_Track5
	db 149	; Note: 45.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 150	; Note: 46.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 151	; Note: 47.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 2	; New instrument: 1.
	db 190	; Short wait: 3.

	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 190	; Short wait: 3.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 45	; Note: 69.
	db 190	; Short wait: 3.


DeckHero_Subsong0_Track6
	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 190	; Short wait: 3.

	db 152	; Note: 48.
	db 8	; New instrument: 4.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.
	db 152	; Note: 48.
	db 10	; New instrument: 5.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 24	; Note: 48.

DeckHero_Subsong0_Track7
	db 173	; Note: 69.
	db 4	; New instrument: 2.
	db 61, 14	; Long wait: 15.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.


DeckHero_Subsong0DisarkByteRegionEnd0
