; Song Untitled in Lightweight format (V1).
; Generated by Arkos Tracker 2.

DEckHero02_Start
DEckHero02_StartDisarkGenerateExternalLabel

DEckHero02_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
DEckHero02_DisarkByteRegionEnd0
DEckHero02_DisarkPointerRegionStart1
	dw DEckHero02_FmInstrumentTable
	dw DEckHero02_ArpeggioTable
	dw DEckHero02_PitchTable
; Table of the Subsongs.
	dw DEckHero02_Subsong0
DEckHero02_DisarkPointerRegionEnd1

; The Arpeggio table.
DEckHero02_ArpeggioTable
DEckHero02_DisarkWordRegionStart2
	dw 0
DEckHero02_DisarkWordRegionEnd2
DEckHero02_DisarkPointerRegionStart3
DEckHero02_DisarkPointerRegionEnd3

; The Pitch table.
DEckHero02_PitchTable
DEckHero02_DisarkWordRegionStart4
	dw 0
DEckHero02_DisarkWordRegionEnd4
DEckHero02_DisarkPointerRegionStart5
DEckHero02_DisarkPointerRegionEnd5

; The FM Instrument table.
DEckHero02_FmInstrumentTable
DEckHero02_DisarkPointerRegionStart6
	dw DEckHero02_FmInstrument0
	dw DEckHero02_FmInstrument1
	dw DEckHero02_FmInstrument2
DEckHero02_DisarkPointerRegionEnd6

DEckHero02_DisarkByteRegionStart7
DEckHero02_FmInstrument0
	db 255	; Speed.

DEckHero02_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
DEckHero02_DisarkPointerRegionStart8
	dw DEckHero02_FmInstrument0Loop	; Loops.
DEckHero02_DisarkPointerRegionEnd8

DEckHero02_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 57	; Volume: 14.

	db 53	; Volume: 13.

	db 49	; Volume: 12.

	db 45	; Volume: 11.

	db 41	; Volume: 10.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
DEckHero02_DisarkPointerRegionStart9
	dw DEckHero02_FmInstrument0Loop	; Loop to silence.
DEckHero02_DisarkPointerRegionEnd9

DEckHero02_FmInstrument2
	db 4	; Speed.

	db 61	; Volume: 15.

	db 57	; Volume: 14.

	db 53	; Volume: 13.

	db 49	; Volume: 12.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 45	; Volume: 11.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
DEckHero02_DisarkPointerRegionStart10
	dw DEckHero02_FmInstrument0Loop	; Loop to silence.
DEckHero02_DisarkPointerRegionEnd10

DEckHero02_DisarkByteRegionEnd7
DEckHero02_Subsong0DisarkByteRegionStart0
; Song Untitled, Subsong 0 - Subsong - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

DEckHero02_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
DEckHero02_Subsong0loop
	db 7	; State byte.
	db 8	; New speed.
	db 63	; New height.
DEckHero02_Subsong0DisarkPointerRegionStart1
	dw DEckHero02_Subsong0_Track0, DEckHero02_Subsong0_Track1, DEckHero02_Subsong0_Track0
DEckHero02_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
DEckHero02_Subsong0DisarkPointerRegionStart2
	dw DEckHero02_Subsong0_Track0, DEckHero02_Subsong0_Track2, DEckHero02_Subsong0_Track3
DEckHero02_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
DEckHero02_Subsong0DisarkPointerRegionStart3
	dw DEckHero02_Subsong0_Track4, DEckHero02_Subsong0_Track2, DEckHero02_Subsong0_Track5
DEckHero02_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
DEckHero02_Subsong0DisarkPointerRegionStart4
	dw DEckHero02_Subsong0_Track6, DEckHero02_Subsong0_Track2, DEckHero02_Subsong0_Track7
DEckHero02_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
DEckHero02_Subsong0DisarkPointerRegionStart5
	dw DEckHero02_Subsong0_Track8, DEckHero02_Subsong0_Track9, DEckHero02_Subsong0_Track10
DEckHero02_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
DEckHero02_Subsong0DisarkPointerRegionStart6
	dw DEckHero02_Subsong0_Track6, DEckHero02_Subsong0_Track11, DEckHero02_Subsong0_Track12
DEckHero02_Subsong0DisarkPointerRegionEnd6
; The tracks.

	db 0	; End of the subsong.
DEckHero02_Subsong0DisarkPointerRegionStart7
	dw DEckHero02_Subsong0loop
DEckHero02_Subsong0DisarkPointerRegionEnd7

; The Tracks.
DEckHero02_Subsong0_Track0
	db 61, 63	; Long wait: 64.


DEckHero02_Subsong0_Track1
	db 213	; Note: 45.
	db 2	; New instrument: 1.
	db 128	; Volume + possible Pitch up/down.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 16	; Note: 40.
	db 62	; Short wait: 1.

	db 21	; Note: 45.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 16	; Note: 40.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 21	; Note: 45.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 62	; Short wait: 1.


DEckHero02_Subsong0_Track2
	db 149	; Note: 45.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 16	; Note: 40.
	db 62	; Short wait: 1.

	db 21	; Note: 45.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 16	; Note: 40.
	db 62	; Short wait: 1.

	db 19	; Note: 43.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 21	; Note: 45.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 35	; Note: 59.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 28	; Note: 52.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 62	; Short wait: 1.


DEckHero02_Subsong0_Track3
	db 225	; Note: 57.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 61, 6	; Long wait: 7.

	db 40	; Note: 64.
	db 61, 6	; Long wait: 7.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.

	db 31	; Note: 55.
	db 61, 6	; Long wait: 7.

	db 40	; Note: 64.
	db 61, 6	; Long wait: 7.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.


DEckHero02_Subsong0_Track4
	db 237	; Note: 69.
	db 2	; New instrument: 1.
	db 128	; Volume + possible Pitch up/down.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 45	; Note: 69.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.


DEckHero02_Subsong0_Track5
	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 61, 6	; Long wait: 7.

	db 40	; Note: 64.
	db 61, 6	; Long wait: 7.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.

	db 31	; Note: 55.
	db 61, 6	; Long wait: 7.

	db 40	; Note: 64.
	db 61, 6	; Long wait: 7.

	db 45	; Note: 69.
	db 61, 14	; Long wait: 15.


DEckHero02_Subsong0_Track6
	db 169	; Note: 65.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.


DEckHero02_Subsong0_Track7
	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 61, 14	; Long wait: 15.

	db 40	; Note: 64.
	db 61, 14	; Long wait: 15.

	db 38	; Note: 62.
	db 61, 14	; Long wait: 15.

	db 43	; Note: 67.
	db 61, 14	; Long wait: 15.


DEckHero02_Subsong0_Track8
	db 173	; Note: 69.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 45	; Note: 69.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 43	; Note: 67.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 79	; Escaped note: 79.
	db 62	; Short wait: 1.

	db 38	; Note: 62.
	db 62	; Short wait: 1.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 63, 76	; Escaped note: 76.
	db 62	; Short wait: 1.

	db 63, 74	; Escaped note: 74.
	db 62	; Short wait: 1.


DEckHero02_Subsong0_Track9
	db 168	; Note: 64.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 38	; Note: 62.
	db 126	; Short wait: 2.

	db 40	; Note: 64.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 190	; Short wait: 3.

	db 31	; Note: 55.
	db 61, 4	; Long wait: 5.

	db 40	; Note: 64.
	db 61, 4	; Long wait: 5.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 40	; Note: 64.
	db 126	; Short wait: 2.

	db 38	; Note: 62.
	db 126	; Short wait: 2.

	db 43	; Note: 67.
	db 190	; Short wait: 3.

	db 40	; Note: 64.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 190	; Short wait: 3.

	db 38	; Note: 62.
	db 61, 4	; Long wait: 5.

	db 40	; Note: 64.
	db 61, 4	; Long wait: 5.

	db 43	; Note: 67.
	db 190	; Short wait: 3.


DEckHero02_Subsong0_Track10
	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 61, 14	; Long wait: 15.

	db 36	; Note: 60.
	db 61, 14	; Long wait: 15.

	db 40	; Note: 64.
	db 61, 14	; Long wait: 15.

	db 38	; Note: 62.
	db 61, 14	; Long wait: 15.


DEckHero02_Subsong0_Track11
	db 168	; Note: 64.
	db 2	; New instrument: 1.
	db 126	; Short wait: 2.

	db 38	; Note: 62.
	db 126	; Short wait: 2.

	db 40	; Note: 64.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 190	; Short wait: 3.

	db 31	; Note: 55.
	db 61, 4	; Long wait: 5.

	db 40	; Note: 64.
	db 61, 4	; Long wait: 5.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 40	; Note: 64.
	db 126	; Short wait: 2.

	db 43	; Note: 67.
	db 126	; Short wait: 2.

	db 45	; Note: 69.
	db 190	; Short wait: 3.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 190	; Short wait: 3.

	db 38	; Note: 62.
	db 61, 4	; Long wait: 5.

	db 40	; Note: 64.
	db 61, 4	; Long wait: 5.

	db 43	; Note: 67.
	db 190	; Short wait: 3.


DEckHero02_Subsong0_Track12
	db 161	; Note: 57.
	db 4	; New instrument: 2.
	db 61, 14	; Long wait: 15.

	db 36	; Note: 60.
	db 61, 14	; Long wait: 15.

	db 40	; Note: 64.
	db 61, 14	; Long wait: 15.

	db 43	; Note: 67.
	db 61, 14	; Long wait: 15.


DEckHero02_Subsong0DisarkByteRegionEnd0
